### ISSUE TITLE
needs work

### ISSUE THREAD

**Issue by TylerAustinW** [Crusader-Boss/Kshitijarya-personal-portfolio#1]
Needs a lot of work, so many things are out of order.

**Comment by Crusader-Boss** [comment]
> Needs a lot of work, so many things are out of order.

yeah man ik i am working on it as we are speaking.

**Comment by TylerAustinW** [comment]
if u need any help let me know, cause you need it bad

**Comment by Crusader-Boss** [comment]
Thanks man i will ask if i do.
